---
- name: Remediate EKS cluster secret encryption
  hosts: localhost
  gather_facts: false
  vars_files: variables.yml
  tasks:
  - name: Get the current caller identity information
    amazon.aws.aws_caller_info:
      profile: "{{ profile }}"
    register: caller_info

  - name: Gather EKS cluster facts
    eks_cluster_facts:
      profile: "{{ profile }}"
      region: "{{ region }}"
      cluster_name: "{{ cluster_name }}"
    register: cluster_info

  - debug:
      msg: "{{ cluster_info }}"

  - name: Create KMS key
    vars:
      encryption_enabled: "{{ 'encryption_config' in cluster_info }}"
    community.aws.aws_kms:
      profile: "{{ profile }}"
      region: "{{ region }}"
      alias: "{{ cluster_info['name'] }}-kms-key"
      policy: "{{ lookup('file','policy/kms_policy.json') | from_json | replace('<ACCOUNT_ID>', caller_info['account']) | replace('<EKS_CLUSTER_ROLE>', cluster_info['role_arn']) }}"
      state: present
    register: kms_key
    when: not encryption_enabled

  - name: Associate KMS key with EKS cluster
    vars:
      encryption_enabled: "{{ 'encryption_config' in cluster_info }}"
    eks_associate_encryption_config:
      profile: "{{ profile }}"
      region: "{{ region }}"
      cluster_name: "{{ cluster_name }}"
      key_arn: "{{ kms_key['key_arn'] }}"
    
    when: not encryption_enabled

  - debug:
      msg: "{{ cluster_info }}"
